### ISSUE TITLE
Make build system use Python3.

### ISSUE THREAD

**Issue by m-kru** [AdaCore/gps#100]
```
make -C gnatstudio default
make[1]: Entering directory '/home/mkru/workspace/gps/gnatstudio'
cd ../kernel/src; python hooks.py
Traceback (most recent call last):
  File "hooks.py", line 2105, in <module>
    generate()
  File "hooks.py", line 1109, in generate
    f.write('''--  Automatically generated from hooks.py
TypeError: a bytes-like object is required, not 'str'
make[1]: *** [Makefile:42: all] Error 1
make[1]: Leaving directory '/home/mkru/workspace/gps/gnatstudio'
make: *** [Makefile:21: all] Error 2
```

This is due to the fact, that build system requires Python2. As of January 1 2020 Python 2 support has been dropped. Can you please update the build system? It has been more than 5 months.

**Comment by godunko** [comment]
Thank you for report. We are working on transition to Python3. Right now, Python 2 is required to build GNAT Studio.
