### ISSUE TITLE
Start with default project.

### ISSUE THREAD

**Issue by Blady-Com** [AdaCore/gps#29]
Hello,

I've got an exception when choosing "Start with default project" in GPS welcome screen:
Welcome to GPS 2018 (20180523) hosted on x86_64-apple-darwin16.7.0
the GNAT Programming Studio
(c) 2001-2018 AdaCore
Traceback (most recent call last):
  File "/usr/local/adacore/2018/share/gps/support/core/cross_references.py", line 177, in on_project_view_changed
    self.recompute_xref()
  File "/usr/local/adacore/2018/share/gps/support/core/cross_references.py", line 158, in recompute_xref
    extra_args = ['--db=%s' % (GPS.xref_db(), )]
GPS.Unexpected_Exception: unexpected internal exception raised GNATCOLL.VFS.VFS_INVALID_FILE_ERROR : gnatcoll-vfs.adb:312
0x0000000115D73DE2 0x000000010ECCB728 0x000000010EFF95FB 0x0000000115447A0E 0x0000000115448E53 0x000000011A7BBAAB 0x000000011A7B7B83 0x000000011A7BEF84 0x000000011A7BB1F1 0x000000011A7B7B83 0x000000011A73B9F9 0x000000011A714AF2 0x000000011A722C73 0x000000011A714AF2 0x0000000115454493 0x000000011545544D 0x0000000115D35E02 0x000000010F052B63 0x000000010F077022 0x000000010F0786F8 0x000000010F07A44D 0x000000010F07A746 0x000000010FFEE4E3 0x000000011714B43D 0x000000011B5BF970 0x000000011B5D0D0A 0x000000011B5D19C6 0x000000011B5D2034 0x000000011A9B19C3 0x000000011B5BFB86 0x000000011B5D170F 0x000000011B5D2034 0x000000011A9B23D4 0x000000011BE96882 0x000000011BE95E9B 0x000000011B5C118B 0x000000011B5BFB86 0x000000011B5D170F 0x000000011B5D2034 0x000000011AA5C16F 0x000000011B5C2AE6 0x000000011B5BFB86 0x000000011B5D170F 0x000000011B5D2034 0x000000011AA5913C 0x000000011AA5A506 0x000000011AA5D9C9 0x000000011AA2EB58 0x000000011ABE230A 0x000000011AAA41AC

HTH, Pascal.

**Comment by Blady-Com** [comment]
Hello Maxim,
No, I haven't any spaces in the path of the current directory.
But I reproduced the error when gps is started in a read only directory.
In addition, here is the end of gps logs when I want to exit:
   [GPS.LANGUAGE.TREE_DATABASE] File's tree is already up-to-date: /usr/local/adacore/2018/share/gps/readonly.gpr (19:27:40.390)
   [GPS.PRJ_EDITOR.OUTLINE] Time elapsed to compute outline: 0.000026000 (19:27:40.390)
   [DISPATCHING] recompute_refs exception unexpected internal exception raised CONSTRAINT_ERROR : gnatcoll-sql-exec.adb:415 access check failed
   _DISPATCHING_ 0x000000010C6B964C 0x000000010C6BA46D 0x000000010C44FCEB 0x0000000105C3A2EC 0x0000000105CE6109 0x000000010C39BA0E 0x000000010C39CE53 0x0000000111945442 0x0000000111940B83 0x0000000111947F84 0x00000001119441F1 0x0000000111948060 0x00000001119441F1 0x0000000111940B83 0x0000000111947F84 0x00000001119441F1 0x0000000111940B83 0x00000001118C49F9 0x000000011189DAF2 0x00000001118ABC73 0x000000011189DAF2 0x000000010C3A8493 0x000000010C3A944D 0x000000010CC84E02 0x0000000105F8EF89 0x0000000106E5AAB3 0x0000000106E5E97C 0x0000000105F9F2FD 0x0000000106B0256D 0x0000000105DB528A 0x0000000105DB5886 0x0000000105DB61B6 0x0000000105DB702A 0x0000000105DB7C29 0x0000000105E44036 0x0000000105FDFF0A 0x0000000105FDB290 0x0000000112570970 0x0000000112581D0A 0x00000001125829C6 0x0000000112583034 0x0000000111D687A7 0x0000000111C480A6 0x0000000111C49247 0x0000000111C2A1AC 0x0000000112570B86 0x000000011258270F 0x0000000112583034 0x0000000111D67F43 0x0000000111C2911E (19:27:40.481)
   [GPS.KERNEL.MDI] Update file info /usr/local/adacore/2018/share/gps/readonly.gpr (19:27:40.481)
   [GPS.KERNEL.GPS_KERNEL] Refresh_Context /usr/local/adacore/2018/share/gps/readonly.gpr (19:27:40.485)
   [GPS.SOURCE_EDITOR.VIEW] Build_Editor_Context (19:27:40.485)
[GPS.KERNEL.ACTIONS] Leaving GPS.Kernel.Actions.Execute_Action:gps-kernel-actions.adb:711 (19:27:40.488)
[GPS.LANGUAGE.TREE_DATABASE] File's tree is already up-to-date: /usr/local/adacore/2018/share/gps/readonly.gpr (19:27:41.406)
[GPS.PRJ_EDITOR.OUTLINE] Time elapsed to compute outline: 0.000012000 (19:27:41.406)
[GPS.KERNEL.GPS_KERNEL] Refresh_Context Messages (19:28:04.083)
[GPS.COMMON.TOOLTIPS] No tooltip to display at this location (19:28:25.159)
[GPS.COMMON.TOOLTIPS] No tooltip to display at this location (19:28:28.847)
[GPS.COMMON.TOOLTIPS] No tooltip to display at this location (19:30:50.272)
[GPS.KERNEL.ACTIONS] Entering GPS.Kernel.Actions.Execute_Action:gps-kernel-actions.adb:711 Execute action exit 1 times synchronous=FALSE (19:30:50.411)
   [GPS.DEBUGGING.BREAKPOINTS] No persistent breakpoint to save (19:30:50.411)
   [GPS.MAIN.WINDOW] Requesting application quit (19:30:50.412)
   [GPS.KERNEL.ACTIONS] Leaving GPS.Kernel.Actions.Execute_Action:gps-kernel-actions.adb:711 (19:30:50.412)
   [GPS.KERNEL.ACTIONS] Entering GPS.Kernel.Actions.Execute_Action:gps-kernel-actions.adb:711 Execute action No casing/indentation on next key 1 times synchronous=FALSE (19:30:50.412)
   [GPS.KERNEL.ACTIONS] Leaving GPS.Kernel.Actions.Execute_Action:gps-kernel-actions.adb:711 (19:30:50.412)
   [GPS.MAIN.GPS] Shutdown (19:30:50.412)
      [GPS.MAIN.GTK.EXCEPTIONS] Unexpected exception: raised GNATCOLL.VFS.VFS_INVALID_FILE_ERROR : gnatcoll-vfs.adb:312
      _GPS.MAIN.GTK.EXCEPTIONS_ 0x000000010CCC2DE2 0x0000000105EBBD19 0x0000000105EEB248 0x00000001054BE652 0x000000010E523CBD 0x0000000112570970 0x0000000112581D0A 0x00000001125829C6 0x0000000112583034 0x00000001122F3229 0x00000001054D4124 0x0000000107013D51 (19:30:50.412)

HTH, Pascal.
