### ISSUE TITLE
Vim plugin - de and ce fail with exception

### ISSUE THREAD

**Issue by TamaHobbit** [AdaCore/gps#49]
Pressing de should delete to the end of the word, ce should edit until the end of the word. Instead, both of these throw:

    Traceback (most recent call last):
      File "C:\Program Files (x86)\Gnatpro\share\gps\library\vim.py", line 751, in key_pressed_proxy
        return view.vim_state.on_key_pressed(view, event)
      File "C:\Program Files (x86)\Gnatpro\share\gps\library\vim.py", line 284, in on_key_pressed
        remember_action = action.apply()
      File "C:\Program Files (x86)\Gnatpro\share\gps\library\vim.py", line 348, in apply
        raise e
    AttributeError: 'NoAction' object has no attribute 'get_start_location'

**Comment by AnthonyLeonardoGracio** [comment]
See answer on #36
